import React , { useEffect } from 'react'
import { IoIosArrowForward, IoIosArrowBack } from "react-icons/io";
import { useNavigate } from 'react-router-dom'
import { motion } from 'framer-motion'

const Botw1 = () => {

  useEffect(() => {

    window.scrollTo(0, 0);
  
  }, []);

    const navigate = useNavigate();

    const handleHome = () => {

        navigate('/');
    
    };

    const handleBotw2 = () => {

        navigate('/botw2');
    
    };

  return (

    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className='mx-auto h-screen max-w-[1240px]'>
        
    <h1 className='text-5xl text-white font-mono p-10 text-center'>Great Plateau</h1>

    <div className='p-20 items-center justify-between'>

    <h2 className='border-b border-gray-500 max-w-full text-4xl text-white'>Great Plateau Tower</h2>

    <p className='text-white text-xl mt-10 mb-10'>The game begins with a voice summoning Link to awake in a desolate cave. Wearing nothing but a pair of shorts, Link will awake within the Shrine of Resurrection. Wander over to the nearby pedestal to collect the Sheikah Slate, a mysterious tablet that will guide you along on your quest. This will trigger a nearby door to open up, so run on through.</p>
    <p className='text-white text-xl mt-10 mb-10'>Here you will find a pair of treasure chests containing an Old Shirt and some Well-Worn Trousers, giving our hero some much needed clothing. Run ahead and hold the Sheikah Slate up to the pedestal, causing the nearby door to open up. Run ahead and climb up the rock wall to get outside, and you’ll find yourself at the Great Plateau. </p>
    <p className='text-white text-xl mt-10 mb-10'>After an overview of the world, Link will see an Old Man in the distance walking towards a camp fire. At this point you can navigate the world as you please; you can find some Tree Branches, Hylian Shrooms, climb up some rocks, interact with your environment, and just get used to your surroundings. You don’t even have to talk to the Old Man if you don’t want to, and he’ll react differently depending on whether you put on clothes yet or if you take things without asking. So begins the complete openness and freedom to do as you please and see what happens which this game offers! This walkthrough will feature our recommended path to take, however.</p>
    <p className='text-white text-xl mt-10 mb-10'>After the title cutscene, make your way over and speak with the Old Man. He talks about the Great Plateau and how it is the birthplace of Hyrule. He gives you a glimpse of the nearby Temple in the distance. If you’d like to, you can run over to these ruins to find the Temple of Time, or continue and explore the world around you. To the northeast of the entrance to the Temple you will find some ruins containing a chest. This contains a pair of Hylian Trousers, which have a defense of three, two more than the previously obtained Well-Worn Trousers.</p>
    <p className='text-white text-xl mt-10 mb-10'>After a while the voice who woke you will speak again and will highlight a spot on the map of your Sheikah Slate. Make your way over to the location and you’ll find various Bokoblins guarding the entry. You can battle them or just run by if you’d like. Place the Sheikah Slate into the pedestal. This will activate the Sheikah Towers found all throughout the land, soaring them into the skies and giving Link a grander view of the region. Link will then appear atop the Great Plateau Tower.</p>
    <p className='text-white text-xl mt-10 mb-10'>Carefully drop down from the Great Plateau Tower and you will once again be joined by the Old Man. He gives you the backstory of Calamity Ganon, who appeared 100 years ago and brought ruin and destruction to the land. The Old Man indicates that you are not able to leave the Plateau unless you have a Paraglider. He offers to trade you as long as you acquire a treasure from a secret Shrine that has appeared in the distance.</p>

    <h2 className='border-b border-gray-500 max-w-full text-4xl text-white'>Oman Au Shrine</h2>

    <p className='text-white text-xl mt-10 mb-10'>This is the first case where the main storyline can be “put on hold”: There are a total of four shrines on the Great Plateau, and while the Old Man is pointing you at the closest, all four will eventually be required, and can be completed in any order, so feel free to take the game how you please. However, the Oman Au Shrine is the closest, so we’ll start there. There are a number of ways to navigate towards the Shrine, but it is a fairly safe route no matter which path you choose.</p>
    <p className='text-white text-xl mt-10 mb-10'>Shrines serve two main functions. Simply arriving at the shrine and putting the Sheikah Slate on the pedestal will unlock the shrine as a quick-warp location, which can be traveled to at any time (even when within a shrine). The secondary function is to enter the shrine and complete it. If you save the shrine for later, the inner portion of the icon will show as red on the map. When all treasure chests within the shrine are collected, a treasure chest icon will show next to its name on the map when it is selected. And finally, shrines that are not unlocked will show as red in the world, shrines that are unlocked but not completed will show as blue with a red top, and completed shrines show as blue.</p>
    <p className='text-white text-xl mt-10 mb-10'>With everything set, go ahead and enter the Oman Au Shrine.</p>
    <p className='text-white text-xl mt-10 mb-10'>Here you will find the Magnesis Trial. Run over to the pedestal and insert the Sheikah Slate to get the Magnesis Rune. This allows Link to interact with and move most metallic objects from a distance. When using the Magnesis Rune, targets made of metal will be highlighted to help find them. Use Magnesis to lift one or both of the two large metallic plates that are on the ground here, revealing a pathway. Drop down below and climb out of the water if you’ve fallen into it. Run ahead and climb the steps.</p>
    <p className='text-white text-xl mt-10 mb-10'>Here you will find a large wall and looking at it, one of the blocks is different than the rest and is made of metal. Another metal block is also in the corner. The rest of the blocks can easily be maneuvered by pushing against them with a metal block using Magnesis. Move the blocks out of the way, or create a staircase over them, and continue.</p>
    <p className='text-white text-xl mt-10 mb-10'>Watch out for the small Guardian Scout I that is roaming around. Guardian enemies do increased damage to any weapon or shield used against them, including bows. You can simply run over and slash away to defeat it, holding up your shield to block its laser beams. Alternatively, you can use Magnesis to control the block and push the enemy down into the water, or even use the large block to smash the guardian.</p>
    <p className='text-white text-xl mt-10 mb-10'>There is one trick to finish off guardians of any type easily, though it requires heavy practice. If you stand in one spot long enough it will aim its focus and shoot a beam at you. The use of the Perfect Guard maneuver can reflect the beam back at it, but if this is not correctly timed, it will do considerable damage to your shield and stronger guardians will likely destroy weaker shields. To use the Perfect Guard Maneuver, focus the target with a shield in hand, and press A to swing your shield. If correctly timed, this will reflect attacks back at the attacker and can also create openings when fighting other enemies. This move is not vital at the start of the game, but quickly becomes so. It is best to practice as much as possible and master it quickly.</p>
    <p className='text-white text-xl mt-10 mb-10'>There is a metal plate on the ground here and it serves as a bridge to the next platform. Run across and then use Magnesis to carry the metal plate over, using it as a bridge to get further across.</p>
    <p className='text-white text-xl mt-10 mb-10'>If you turn to the left you can see a treasure chest on a higher platform. Use Magnesis to grab the treasure chest and pull it towards you. Open it up to get a Traveler’s Bow. Up ahead there are two massive metallic doors. Use Magnesis to pull the doors open, allowing you to pass.</p>
    <p className='text-white text-xl mt-10 mb-10'>Run ahead and examine the altar to speak with the Monk, Oman Au. He is the Monk of this Shrine and as a reward for your completing his trial, he will give you a Spirit Orb. A Monk will be found at the end of every shrine.</p>
    <p className='text-white text-xl mt-10 mb-10'>You will then be warped back to outside of the Shrine. At this point, now that you have the Magnesis Rune, you can interact with all sorts of objects in the Overworld. You can control large boxes and toss them into the air, which upon destruction will give rewards. You can also pull up metallic treasure chests from underwater to uncover some more goodies. Some treasure chests, particularly in grassy areas, may be half buried, and can be pulled up with this rune. As always, the key here is explore, explore, explore!</p>

    <h2 className='border-b border-gray-500 max-w-full text-4xl text-white'>Ja Baij Shrine</h2>

    <p className='text-white text-xl mt-10 mb-10'>Once you complete the first Shrine, the Old Man will paraglide over. He informs you that you can warp over to previous locations that you’ve uncovered with the Sheikah Slate, including the Great Plateau Tower, as well as Shrines. He tells you to meet him back up at the top of the tower, so pull out your Sheikah Slate and warp on over. </p>
    <p className='text-white text-xl mt-10 mb-10'>The Old Man is already here. Odd? Talk to him and he’ll teach you about the scope ability of your Sheikah Slate. He suggests looking out into the distance so that you can pinpoint the location of the other three shrines in the area. All three of them are easily visible from the Great Plateau Tower, but they can also be easy to miss. Note that the scope does not have a zoom in or out function so often it’s better to use the normal camera for looking around and the scope specifically when you want to place a pin.</p>
    <p className='text-white text-xl mt-10 mb-10'>The closest of the shrines is nearby at the east end of the Great Plateau. It is located in a bit of a maze area that is surrounded by a couple of inactive Guardians. However, as you draw near, these Guardians will awaken and will shoot a massive beam of energy towards you after locking on. The path to the shrine is blocked off by a large boulder. The easiest way to access the shrine is to simply climb over the wall, though this can be tough if a Guardian has locked on to you. Alternatively, you can use the Guardian’s beam to blast through the boulder, but that is much more difficult. </p>
    <p className='text-white text-xl mt-10 mb-10'>Once beyond the wall, place the Sheikah Stone into the pedestal to open the entrance to the next Shrine.</p>
    <p className='text-white text-xl mt-10 mb-10'>Here we are at Ja Baij Shrine, also known as the Bomb Trial. Run over and place the Sheikah Stone into the pedestal and you’ll acquire the Remote Bomb Rune. This will allow Link to use Remote Bombs, in both the spherical form we all know and love, as well as a new cubic form. The difference between the two bombs is that spherical bombs will of course roll, and cubic bombs don’t. Use cubic bombs when you want to make sure the bomb doesn’t move out of place, for instance. Other than that there is no difference between either bomb. And for a final bonus, these bombs do not have a timed fuse like in previous games. Instead, they only explode when they are triggered remotely, by the rune. As these bombs are magical, they are infinite in supply, however a short cooldown is required between each use.</p>
    <p className='text-white text-xl mt-10 mb-10'>As an advanced technique, it is possible to get a bomb out, switch to another rune, and then later switch back to the bomb rune and detonate it then. Since there are two bomb runes, this means you can have one of each out at a time, detonating one or the other as needed, by switching between the two Runes in the Sheikah Slate.</p>
    <p className='text-white text-xl mt-10 mb-10'>In the first room there are a pair of boulders that can be blown up using your new rune. Take the path to the right and blow up some more boulders to find a treasure chest that contains a Traveler’s Claymore.</p>
    <p className='text-white text-xl mt-10 mb-10'>Blow up up the boulders that were on the left and climb the ladder to progress onward to the next room. Here you will find a moving platform and there are some more large boulders that are blocking your path. You want to use a cube bomb here so that it won’t roll off the moving platform. Place the bomb at the edge of the moving platform and then return to a safe distance. When the platform moves next to the boulders, blow it up to get by.</p>
    <p className='text-white text-xl mt-10 mb-10'>In the next area, you will see some devices that shoot out in a direction. The first one you see on the right has a small tunnel where you can drop a spherical bomb into. The bomb will launch across the room and you can detonate the bomb to blast away some blocks.</p>
    <p className='text-white text-xl mt-10 mb-10'>Before progressing, head to the other side of the room where there are a pair of these launching devices. You can have one of them launch you to the other side to reach another treasure chest that contains a piece of Amber.</p>
    <p className='text-white text-xl mt-10 mb-10'>Now drop down to the ground floor and make your way over to the ladder. With the boulders above now out of the way, climb on up and make your way over to the Monk. Just like the Monk from the previous Shrine, he will bestow upon you a Spirit Orb and return you to the surface.</p>
    <p className='text-white text-xl mt-10 mb-10'>With the Bomb Rune, another flood of possibilities is open to you in your exploration. You can now wander around the Great Plateau, using your Remote Bombs in various ways to find a wide variety of goodies.</p>

    <h2 className='border-b border-gray-500 max-w-full text-4xl text-white'>Owa Daim Shrine</h2>

    <p className='text-white text-xl mt-10 mb-10'>The Owa Daim Shrine is located at the south-central portion of the Great Plateau, at the south-eastern edge of the Mount Hylia region of the map, and is our next destination. This shrine, along with the final shrine in this area, are both located near colder climates, and Link will begin to take damage if he doesn’t have the proper gear or food. In our walkthrough we will first head towards the Temple of Time near the center of the map and get what we need to resist the cold, in order to make it easier to get to the fourth shrine, later.</p>
    <p className='text-white text-xl mt-10 mb-10'>(Note that the Owa Daim Shrine can be reached directly via other methods, such as cutting down a tree to fall across a chasm, as one example, and cold resistance is not required. There are various ways to get cold resistance for the fourth shrine along that route, too. But this walkthrough couldn’t possibly cover all the options you have in front of you! So as always, feel free to explore and find your own way whenever you please!)</p>
    <p className='text-white text-xl mt-10 mb-10'>From the Temple of Time head westward and you will see an archway that leads to a snowy plain. Just next to the archway there are some Spicy Peppers, so be sure to grab them. Before heading into the snow, walk northward a bit and you’ll see a Bokoblin camp. It’s a good idea to get rid of these enemies so that you can do some cooking. There are more spicy peppers in this area and it is recommended to pick them up too. Use a Boko Club or a Tree Branch and light it on fire, and then use that flame to light up the fire beneath the pot.</p>
    <p className='text-white text-xl mt-10 mb-10'>Go into your inventory and select those Spicy Peppers you just obtained. You can hold up to 5 of them at a time and if you throw them all into the pot you can cook up some Spicy Sautéed Peppers. Five of them will allow you to have low-level cold resistance for over 12 minutes, which should give you plenty of time to navigate through the higher elevation regions of the Great Plateau. You can also experiment and create other recipes as well by mixing and matching ingredients, however if you include at least one Spicy Pepper, your result is likely to still give some amount of cold resistance. Cooking is pretty self explanatory; reading the description of each cooking material will give you a pretty accurate idea of what the results will be for combining various items (or multiple of the same item, such as with Spicy Sautéed Peppers.)</p>
    <p className='text-white text-xl mt-10 mb-10'>There are other ways to survive the cold, too! If in your travels you have come across a Warm Doublet (an option for how to get this item is later in this chapter), that will also provide cold resistance when worn. You can also carry a lit torch, although it is easy to accidentally put it away or break it when fighting, and then it may not be easy to light it again. Another option is to collect a lot of food and then continuously eat it all as you take damage from the cold while quickly traveling to your destination. This cannot be said enough, but there are many ways to accomplish objectives in this game, so feel free to come up with your own!</p>
    <p className='text-white text-xl mt-10 mb-10'>For this guide though, cook and eat some food to get cold resistance, and then run through the gate to reach the colder area. It’s now time to make your way over to the Owa Daim Shrine. By coming from this direction, you can climb higher up and then strategically climb down right when you are near the shrine. Be sure to check our Interactive Map if you aren’t sure of the exact location of the shrine. As per usual, once you arrive use the Sheikah Slate on the pedestal to open up the entrance.</p>
    <p className='text-white text-xl mt-10 mb-10'>Inside, run over to the Pedestal and place your Sheikah Slate to get the Rune for this shrine. This will give you the Stasis ability, which allows Link to freeze objects in time for a short period. These objects can also be hit to store kinetic energy and when time resumes, this energy will be expelled all at once, which can cause even the largest of objects to get launched across a room.</p>
    <p className='text-white text-xl mt-10 mb-10'>The massive gear on the left side of the room is causing the nearby platform to rotate. Wait until the platform is level and then use Stasis on the gear, freezing it in time momentarily. Quickly run across before the gear re-activates.</p>
    <p className='text-white text-xl mt-10 mb-10'>Run ahead and you’ll see a massive ball rolling down a narrow bridge. Once the ball passes you, quickly run up the bridge. Look ahead and you’ll see a second ball ready to roll down. Use Stasis to freeze it momentarily and quickly run up the bridge and off to the side to avoid the ball.</p>
    <p className='text-white text-xl mt-10 mb-10'>Before progressing further, there is still a treasure for us to find here. Wait until the ball rolls by and then quickly run up to the top of the ramp where the balls first appear. Here you will find a treasure chest containing a Traveler’s Shield.</p>
    <p className='text-white text-xl mt-10 mb-10'>Run ahead and you’ll see a large Iron Sledgehammer sitting against the wall. Be sure to pick it up as we’ll need a heavy duty weapon. Up ahead the path is blocked off by a stationary ball in the middle of the ramp. Use Stasis to freeze the object. In the few moments before it re-activates, use the Iron Sledgehammer to hit the ball several times. This will store the energy and once time resumes, the ball will be launched ahead.</p>
    <p className='text-white text-xl mt-10 mb-10'>At this point you can run ahead to reach the Monk. Like the previous ones, he will give you a Spirit Orb for completing the trial.</p>
    <p className='text-white text-xl mt-10 mb-10'>Back in the Overworld, the Stasis ability can be used on a variety of objects. It’s fun to use it on the nearby rock and launch it all the way across the map, for instance, and be rewarded with the chest underneath. Once more the possibilities for exploration have opened up even further to you. Feel free to get sidetracked as much as you like (that’s what this whole game is about after all), and when you’re ready, we’ll move on to the next Shrine.</p>

    <h2 className='border-b border-gray-500 max-w-full text-4xl text-white'>Keh Namut Shrine</h2>

    <p className='text-white text-xl mt-10 mb-10'>The Keh Namut Shrine is located at the west portion of the Great Plateau, just to the west of the River of the Dead and northwest of Mount Hylia. The Shrine is located at one of the local peaks of the mountain in this area, just near a small lake. The area around the Shrine is cold, so once again, be sure to get cold resistance in some way, such as cooking up some Spicy Sautéed Peppers. The River of the Dead is the biggest obstacle on the path to reach this shrine. All routes across the river are a tad bit difficult, so your best bet is to simply go around the south edge. But once more, feel free to find your own way, and continue this walkthrough once you reach the shrine however you like!</p>
    <p className='text-white text-xl mt-10 mb-10'>If you are coming from the Owa Daim Shrine, immediately just climb the west wall to get to a much higher peak and it’s a pretty straight forward route from here. Otherwise, make your way to the Temple of Time near the center of the Great Plateau and travel westward through the archway. Travel around the south end of the River of the Dead and begin to scale the mountain.</p>
    <p className='text-white text-xl mt-10 mb-10'>Before heading to Keh Namut Shrine, make your way up to the peak of Mount Hylia. At the top of the mountain you will find the Old Man. He is impressed that you were able to make it this far and he’ll give you the Warm Doublet, which is an upgraded tunic that is resistant to the colder environment that we mentioned earlier. Be sure to also examine the nearby rock to get some Amber. Now make your way over to the Keh Namut Shrine.</p>
    <p className='text-white text-xl mt-10 mb-10'>(Note, this method of getting the Warm Doublet is only available during this chapter. Other methods are also available, for explorers intrepid enough to find them. After this chapter however, you can visit the log cabin south of the Owa Daim Shrine to get the Warm Doublet from a chest, or buy it from a store elsewhere in the world.)</p>
    <p className='text-white text-xl mt-10 mb-10'>You will arrive at the Keh Namut Shrine, otherwise known as the Cryonis Trial. Run on over to the pedestal and place your Sheikah Slate to get it infused with the Cryonis Rune. This will give Link the Cryonis ability, which allows Link to build ice pillars. There is a small pond of water and if you use Cryonis, you can create a pillar of ice. Climb up the ice and onto the adjacent platform.</p>
    <p className='text-white text-xl mt-10 mb-10'>Run ahead and you’ll find a gate that is just above a pond of water. Use Cryonis to create an ice pillar right underneath the gate, and the pillar will cause the gate to rise up, allowing you to pass. This is an ability of Cryonis that often gets forgotten, so make sure to remember it when you’re trying to figure out puzzles!</p>
    <p className='text-white text-xl mt-10 mb-10'>You’ll then run into another Guardian Scout I. Since there is water here, a new combat option is to use Cryonis to create an ice pillar, preventing its beam from hitting you. Run on over and defeat the enemy. Just to the side there is a small nook that contains a treasure chest. Uses Cryonis to create a pillar and climb up to reach the treasure chest holding a Traveler’s Spear.</p>
    <p className='text-white text-xl mt-10 mb-10'>At the end of this path, you’ll find a platform that is lying on the ground. Just beneath it on the right, use Cryonis to create a pillar, causing the platform to turn into a ramp and allow you to climb up it.</p>
    <p className='text-white text-xl mt-10 mb-10'>Run over to the end of the Shrine where you will find the Monk. Just as the previous Monks, Keh Numut will give you a Spirit Orb for completing the trial.</p>
    <p className='text-white text-xl mt-10 mb-10'>Once you exit the Shrine, you can get a nearby treasure chest that was surrounded by water by using Cryonis to reach it. Once more, your ability to explore has been increased. Cryonis is great for crossing any body of water, including ones that may be too far or have too strong a current to swim. You can use the ability wherever you see water and it will allow you to reach an assortment of new areas.</p>

    <h2 className='border-b border-gray-500 max-w-full text-4xl text-white'>The Paraglider</h2>

    <p className='text-white text-xl mt-10 mb-10'>Once you complete all four shrines, the Old Man will once again appear. He tells you that you should imagine an X on your map, with the four shrines as the end points. Find the spot where those lines intersect. That location would be the Temple of Time, located right near the center of the Great Plateau. You can warp over to the Shrine of Resurrection, or just make your way down the mountain. This will complete the Isolated Plateau objective.</p>
    <p className='text-white text-xl mt-10 mb-10'>Once you arrive at the Temple of Time, run inside and you will see a shining Goddess Statue. Whenever you have four or more Spirit Orbs, you can find a Goddess Statue and pray to it. As a trade for four Spirit Orbs, you can upgrade your Stamina Vessel, or you can get a Heart Container. Either one is a good choice at this point.</p>
    <p className='text-white text-xl mt-10 mb-10'>After communicating with the statue, the Old Man will call out from atop the Temple of Time. Go outside and climb up to the top of the Temple. One method is to go to the front of the temple, and then from outside, face it, and then climb the corner on your left. Run over and speak with the Old Man, who will reveal a bit more about what the heck is going on in the world. He will then finally give Link the Paraglider, allowing you to finally leave the Great Plateau.</p>
    <p className='text-white text-xl mt-10 mb-10'>After the cut-scene, two new Main Quests open up in your Adventure Log. The first one is Destroy Ganon, which is the last thing that you will need to do in the main quest. Technically, you can venture directly to Hyrule Castle now and take on the final boss. However, we are far from prepared to do so, but the game does give you this option. The other Main Quest is to Seek Out Impa, and that is where we will go in the next chapter.</p>
    <p className='text-white text-xl mt-10 mb-10'>Also note, amiibo are now free to use. The option to use them will need to be turned on in the settings menu. You will need to switch to the amiibo ‘rune’, aim at an acceptable place on the ground, and then tap the amiibo to use it. All amiibos that exist will grant some kind of reward and can be used once per real life day, each, although only amiibo related to the Zelda franchise give the exclusive rewards. The exception is the Wolf Link amiibo; if he dies he may not be summoned again for another day, but otherwise he can be summoned as many times as you like. For more information, see the Breath of the Wild Amiibo wiki page.</p>

    <div className='mx-auto grid md:grid-cols-2 gap-8'>

    <button onClick={handleHome} className='h-15 w-[10vw] mx-auto flex flex-col items-center justify-center border border-gray-500 rounded-lg hover:bg-gray-400'>

    <div className='flex items-center justify-center mx-auto mt-2 mb-2 text-white text-2xl'> <IoIosArrowBack/> Previous </div>
    <p className='items-center mt-2 text-xl text-white'>Home</p>

    </button>

    <button onClick={handleBotw2} className='h-15 w-[10vw] mx-auto flex flex-col items-center justify-center border border-gray-500 rounded-lg hover:bg-gray-400'>

    <div className='flex items-center mx-auto mt-2  text-white text-2xl'> Next <IoIosArrowForward/> </div>
    <p className='items-center mt-2 mb-2 text-xl text-white'>Dueling Peaks</p>

    </button>

    </div>

    </div>

    </motion.div>

  )


}

export default Botw1